<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="1" failures="0" skipped="0" tests="1" time="1.810" timestamp="2025-06-18T12:27:20.083597+02:00" hostname="ocean"><testcase classname="pytest" name="internal" time="0.000"><error message="internal error">Traceback (most recent call last):
  File "/Users/thomas/Programming/versiontracker/.venv/lib/python3.12/site-packages/_pytest/main.py", line 283, in wrap_session
    session.exitstatus = doit(config, session) or 0
                         ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/thomas/Programming/versiontracker/.venv/lib/python3.12/site-packages/_pytest/main.py", line 336, in _main
    config.hook.pytest_collection(session=session)
  File "/Users/thomas/Programming/versiontracker/.venv/lib/python3.12/site-packages/pluggy/_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/thomas/Programming/versiontracker/.venv/lib/python3.12/site-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/thomas/Programming/versiontracker/.venv/lib/python3.12/site-packages/pluggy/_callers.py", line 139, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/Users/thomas/Programming/versiontracker/.venv/lib/python3.12/site-packages/pluggy/_callers.py", line 122, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/thomas/Programming/versiontracker/.venv/lib/python3.12/site-packages/_pytest/logging.py", line 790, in pytest_collection
    return (yield)
            ^^^^^
  File "/Users/thomas/Programming/versiontracker/.venv/lib/python3.12/site-packages/pluggy/_callers.py", line 122, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/thomas/Programming/versiontracker/.venv/lib/python3.12/site-packages/_pytest/warnings.py", line 121, in pytest_collection
    return (yield)
            ^^^^^
  File "/Users/thomas/Programming/versiontracker/.venv/lib/python3.12/site-packages/pluggy/_callers.py", line 122, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/thomas/Programming/versiontracker/.venv/lib/python3.12/site-packages/_pytest/config/__init__.py", line 1417, in pytest_collection
    return (yield)
            ^^^^^
  File "/Users/thomas/Programming/versiontracker/.venv/lib/python3.12/site-packages/pluggy/_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/thomas/Programming/versiontracker/.venv/lib/python3.12/site-packages/_pytest/main.py", line 347, in pytest_collection
    session.perform_collect()
  File "/Users/thomas/Programming/versiontracker/.venv/lib/python3.12/site-packages/_pytest/main.py", line 819, in perform_collect
    hook.pytest_collection_finish(session=self)
  File "/Users/thomas/Programming/versiontracker/.venv/lib/python3.12/site-packages/pluggy/_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/thomas/Programming/versiontracker/.venv/lib/python3.12/site-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/thomas/Programming/versiontracker/.venv/lib/python3.12/site-packages/pluggy/_callers.py", line 139, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/Users/thomas/Programming/versiontracker/.venv/lib/python3.12/site-packages/pluggy/_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/thomas/Programming/versiontracker/.venv/lib/python3.12/site-packages/_pytest/terminal.py", line 851, in pytest_collection_finish
    self._printcollecteditems(session.items)
  File "/Users/thomas/Programming/versiontracker/.venv/lib/python3.12/site-packages/_pytest/terminal.py", line 881, in _printcollecteditems
    self._tw.line(f"{indent}{col}")
  File "/Users/thomas/Programming/versiontracker/.venv/lib/python3.12/site-packages/_pytest/_io/terminalwriter.py", line 180, in line
    self.write(s, **markup)
  File "/Users/thomas/Programming/versiontracker/.venv/lib/python3.12/site-packages/_pytest/_io/terminalwriter.py", line 165, in write
    self._file.write(msg)
BrokenPipeError: [Errno 32] Broken pipe</error></testcase></testsuite></testsuites>
